### ISSUE TITLE
identifyPanel widget, export button issue

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#138] opened 2017-08-17 17:53 UTC
the dialog box is maximized. Not sure if there is any setting we can use to change that.

I am using the most current Develop version. (very good enhancement!)

Thanks.

ERS-Long

**Comment by tmcgee** [comment] 2017-08-18 07:27
@ERS-Long This is something I noticed the other day and is actually a CMV bug introduced in the latest commits. The fix that I will submit is to change [this line](https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_WidgetsMixin.js#L300) to this:

``` javascript
class: parentId + ' ' + widgetConfig.type + 'Widget',
```

Of course there is always more than one way to skin a cat. You can include a style property in the widget's options to set the width and height. That's true for pretty much any widget. Something like this:

``` javascript
style: 'width: 285px;height:320px;max-width:98vw;max-height:98vw',
```

or for the floating pane itself as we do for [help widget](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L663)

Since the issue is specific to CMV and not the widgets themselves, I am going to close this issue.

**Closed as completed by tmcgee** 2017-08-18 07:27 UTC
