### ISSUE TITLE
Issue in add & remove layer

### ISSUE THREAD

**Issue by AbdulSamim** [tmcgee/cmv-widgets#175] opened 2018-04-05 08:42 UTC
Hi @tmcgee ,

1.While removing layer from map using this code inside LayerControl.js
this.map.removeLayer(control.layer) required layer is removed from the map viewer, but still this.layerInfos having information of removed layers.
OR I am using (layerControl/removeLayerControls) in this case layer is not removed from
Map and TOC

_Removeservice: function (control) {
var layerControlInfo = {
controlOptions: {
expanded: false,
noLegend: true,
metadataUrl: false,
swipe: false
},
layer: control.layer,
title: control.layer.id,
type: 'dynamic'
};

        topic.publish('layerControl/removeLayerControls', [layerControlInfo]);
}

2.While adding dynamic service programmatically in map viewer it is adding but in TOC not getting updated.

var imageParameters = new ImageParameters();
imageParameters.layerIds = visibleLayers;
imageParameters.layerOption = ImageParameters.LAYER_OPTION_SHOW;
imageParameters.transparent = true;

var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(url,
{ "imageParameters": imageParameters });
this.map.addlayer(dynamicMapServiceLayer);

                 var layerControlInfo = {
                     controlOptions: {
                         expanded: false,
                         noLegend: true,
                         metadataUrl: false,
                         swipe: false
                     },
                     layer: dynamicMapServiceLayer,
                     title: 'Cities',

                     type: 'dynamic'
                 };
                 topic.publish('layerControl/addLayerControls', [layerControlInfo]);

Please let me know how to update/refresh layercontrol after adding or removing service/layer from the map.

Any lead on this will be of great help.
Thanks in Advance.
Samim

**Comment by tmcgee** [comment] 2018-04-05 14:16
duplicate of #173.

**Closed as completed by tmcgee** 2018-04-05 14:16 UTC
